/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.CVentas;
import Backend.Conexion;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s2212
 */
public class Crud_Ventas extends javax.swing.JFrame {

    Conexion cx;
    CVentas n= new CVentas();
    String user;
    String f;
    int idUser;
    int idCliente;
    String NombreDeCliente;
    double total;
    double iva;
    //Hacemos el constructor
    public Crud_Ventas(String nombre) {
        initComponents();
        //El JFrame este centrado
        setLocationRelativeTo(null);
        //El JFrame tenga un tama;o fijo
        this.setSize(910, 650);
        //El usuario no pueda modificar el tama;o del JFrame
        this.setResizable(false);
        cx = new Conexion("Costco");
        this.user=nombre;
        this.idUser=n.idUser(user);
        // Tener la fecha 
        LocalDate fecha = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-MM-dd");
         f = fecha.format(formato);
        TxtFecha.setText(f);
        TxtNombre.setText(n.name(user));
        ArrayList<String> nombresDeClientes = n.selectNombresClientes();
        // Limpiar el ComboBox en caso de que ya tenga elementos previos
        cmbCliente.removeAllItems();
        // Agregar cada nombre al ComboBox
        for (String nombre1 : nombresDeClientes) {
            cmbCliente.addItem(nombre1);
        }
        this.idCliente=n.SelectIDCliente((String) cmbCliente.getSelectedItem());
        this.NombreDeCliente=(String) cmbCliente.getSelectedItem();
    }
    public Crud_Ventas () {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void actualizarTotales() {
         double subtotal = 0.0;
    
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object importeObj = modelo.getValueAt(i, 4); // Columna de importe
            if (importeObj != null && importeObj instanceof Double) {
                subtotal += (double) importeObj;
            }
        }

         iva = subtotal * 0.16; 
        total = subtotal + iva;

        String[] totales = {
            "$ "+String.format("%.2f", subtotal),
            "$ "+String.format("%.2f", iva),
            "$ "+String.format("%.2f", total)
        };
        lista.setListData(totales);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMas = new javax.swing.JButton();
        brnMenos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminarT = new javax.swing.JButton();
        TxtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMas.setBackground(new java.awt.Color(255, 0, 0));
        btnMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Venta/mas.png"))); // NOI18N
        btnMas.setPreferredSize(new java.awt.Dimension(150, 100));
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 60, 60));

        brnMenos.setBackground(new java.awt.Color(255, 0, 0));
        brnMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Venta/menos.png"))); // NOI18N
        brnMenos.setPreferredSize(new java.awt.Dimension(150, 100));
        brnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnMenosActionPerformed(evt);
            }
        });
        jPanel1.add(brnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 60, 60));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Venta/Eliminar.png"))); // NOI18N
        btnEliminar.setPreferredSize(new java.awt.Dimension(150, 100));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 70, 60));

        btnEliminarT.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Venta/EliminarT.png"))); // NOI18N
        btnEliminarT.setPreferredSize(new java.awt.Dimension(150, 100));
        btnEliminarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 60, 60));

        TxtFecha.setBackground(new java.awt.Color(204, 204, 204));
        TxtFecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TxtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtFecha.setEnabled(false);
        TxtFecha.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Empleado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 100, -1));

        TxtNombre.setBackground(new java.awt.Color(204, 204, 204));
        TxtNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TxtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtNombre.setEnabled(false);
        TxtNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Menu/cerrar-sesion.png"))); // NOI18N
        btnSalir.setPreferredSize(new java.awt.Dimension(150, 100));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");

        btnSalir1.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Menu/reiniciar.png"))); // NOI18N
        btnSalir1.setPreferredSize(new java.awt.Dimension(150, 100));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REGRESAR");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40))
                    .addComponent(btnSalir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55))
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 150));

        txtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscar.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Borrar Uno");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 80, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Borar Todos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 90, 20));

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Precio", "Cantidad", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 650, 270));

        lista.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lista.setForeground(new java.awt.Color(204, 204, 204));
        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "$ 0.00", "$ 0.00", "$ 0.00", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setEnabled(false);
        lista.setSelectionForeground(new java.awt.Color(204, 204, 204));
        lista.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(lista);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 90, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subtotal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("IVA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, 20));

        btnAceptar.setBackground(new java.awt.Color(204, 204, 255));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Venta/aceptar.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 100, 80));

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 200, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cliente: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, -1));

        btnEliminar1.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("AUDITORIA");
        btnEliminar1.setPreferredSize(new java.awt.Dimension(150, 100));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 120, 60));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Background.jpg"))); // NOI18N
        lblbackground.setPreferredSize(new java.awt.Dimension(960, 610));
        jPanel1.add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        cx.conectar();
        cx.desconectar();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        Menu menu = new Menu(user);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        int selecionaLaFila = jTable1.getSelectedRow();  
        if (selecionaLaFila != -1) {
            String CodigoDeProducto=(String) jTable1.getValueAt(selecionaLaFila, 0);
            Object[] producto = n.buscarProductoPorCodigo(CodigoDeProducto);
            if(producto !=null){
                int cantidadDisponible = (int) producto[3];
                int cantidad = Integer.parseInt(jTable1.getValueAt(selecionaLaFila, 3).toString());
                if(cantidad<cantidadDisponible){
                     cantidad++;
                     jTable1.setValueAt(cantidad, selecionaLaFila, 3);
                     double precio = Double.parseDouble(jTable1.getValueAt(selecionaLaFila, 2).toString()); 
                     double importe = cantidad * precio;
                     jTable1.setValueAt(importe, selecionaLaFila, 4); 
                     actualizarTotales();
                }else{
                         JOptionPane.showMessageDialog(this, "No puedes agregar más de la cantidad disponible en la base");
                }
            
            }  else{
                JOptionPane.showMessageDialog(null, "El producto no está disponible o está descontinuado.");
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Por favor Seleccione una fila.");
        }
       
    }//GEN-LAST:event_btnMasActionPerformed

    private void brnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnMenosActionPerformed
        int selecionaLaFila = jTable1.getSelectedRow();
        System.out.println(idCliente);
        if (selecionaLaFila != -1) {
            int cantidad = Integer.parseInt(jTable1.getValueAt(selecionaLaFila, 3).toString());
            if (cantidad > 1) {
                cantidad--;  
                jTable1.setValueAt(cantidad, selecionaLaFila, 3); 
                double precio = Double.parseDouble(jTable1.getValueAt(selecionaLaFila, 2).toString()); 
                double importe = cantidad * precio;
                
                jTable1.setValueAt(importe, selecionaLaFila, 4); 
                actualizarTotales();
            } else if (cantidad == 1) {
                
                ((DefaultTableModel) jTable1.getModel()).removeRow(selecionaLaFila);
                actualizarTotales();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor Seleccione una fila.");
        }
    }//GEN-LAST:event_brnMenosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int selecionaLaFila = jTable1.getSelectedRow(); 
          if (selecionaLaFila != -1) {
              int cantidad = Integer.parseInt(jTable1.getValueAt(selecionaLaFila, 3).toString());
               ((DefaultTableModel) jTable1.getModel()).removeRow(selecionaLaFila);
               actualizarTotales();
          }else {
            JOptionPane.showMessageDialog(null, "Por favor Seleccione una fila.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
         modelo.setRowCount(0);
        actualizarTotales();
    }//GEN-LAST:event_btnEliminarTActionPerformed

    private void TxtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        try {
            String Codigo = txtBuscar.getText().trim();

            Object[] producto = n.buscarProductoPorCodigo(Codigo);

            if (producto != null) {
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                int cantidadDisponible=(int) producto[3];
                boolean productoE = false;
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    Object FilaObj = modelo.getValueAt(i, 0);

                    if (FilaObj != null && FilaObj instanceof String) {
                        String idDeFila = (String) FilaObj;
                        if (idDeFila.equals(Codigo)) {
                            int cantidad = (int) modelo.getValueAt(i, 3);
                            double precioUnitario = (double) modelo.getValueAt(i, 2);
                            if (cantidad < cantidadDisponible){
                                cantidad += 1;
                                modelo.setValueAt(cantidad, i, 3);
                                double nuevoImporte = cantidad * precioUnitario;
                                modelo.setValueAt(nuevoImporte, i, 4);
                            }else{
                                JOptionPane.showMessageDialog(this, "No puedes agregar más de la cantidad disponible en la base");
                            }

                            productoE = true;
                            break;
                        }
                    }
                }
                if (!productoE) {
                    if(1<=cantidadDisponible){
                        Object[] nuevaFila = {
                            producto[0],
                            producto[1],
                            producto[2],
                            1,
                            (double) producto[2]
                        };
                        modelo.addRow(nuevaFila);
                    }else{
                        JOptionPane.showMessageDialog(this, "No puedes agregar más de la cantidad disponible en la base");
                    }

                }
                actualizarTotales();
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado o descontinuado");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un Codigo de producto válido");
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        if(modelo.getRowCount() == 0){
               JOptionPane.showMessageDialog(this, "Haz una venta");
        }else{
            n.realizarTransaccion( modelo,idUser,idCliente,f,total,n.name(user),iva,NombreDeCliente);
            modelo.setRowCount(0);
            txtBuscar.setText("");
            actualizarTotales();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        Auditoria c = new Auditoria(user);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton brnMenos;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminarT;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
