/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Conexion;
import javax.swing.JOptionPane;
import Backend.CClientes;
import java.util.List;

/**
 *
 * @author s2212
 */
public class Crud_Clientes extends javax.swing.JFrame {

    Conexion cx;
    CClientes c;
    String user;
    public Crud_Clientes(String nombre) {
        initComponents();
        //El JFrame este centrado
        setLocationRelativeTo(null);
        //El JFrame tenga un tama;o fijo
        this.setSize(910, 650);
        //El usuario no pueda modificar el tama;o del JFrame
        this.setResizable(false);
        c= new CClientes();
        cx = new Conexion("Costco");
        this.user=nombre;
    }
     public Crud_Clientes () {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();
        lblbackground1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES");

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Menu/cerrar-sesion.png"))); // NOI18N
        btnSalir.setPreferredSize(new java.awt.Dimension(150, 100));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");

        btnSalir1.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Menu/reiniciar.png"))); // NOI18N
        btnSalir1.setPreferredSize(new java.awt.Dimension(150, 100));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REGRESAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40))
                    .addComponent(btnSalir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55))
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 150));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Crud/eliminar.png"))); // NOI18N
        btnEliminar.setPreferredSize(new java.awt.Dimension(150, 100));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        btnEditar.setBackground(new java.awt.Color(255, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Crud/editar-informacion.png"))); // NOI18N
        btnEditar.setPreferredSize(new java.awt.Dimension(150, 100));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 0, 0));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Crud/agregar-usuario (1).png"))); // NOI18N
        btnAgregar.setPreferredSize(new java.awt.Dimension(150, 100));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Img-Crud/buscar.png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(150, 100));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 240, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE COMPLETO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMAIL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 240, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 240, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENERO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel1.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 240, 50));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 240, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DIRECCION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Background.jpg"))); // NOI18N
        lblbackground.setPreferredSize(new java.awt.Dimension(960, 610));
        jPanel1.add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 900, -1));

        lblbackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Background.jpg"))); // NOI18N
        lblbackground1.setPreferredSize(new java.awt.Dimension(960, 610));
        jPanel1.add(lblbackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        cx.conectar();
        cx.desconectar();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        Menu menu = new Menu(user);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!txtNombre.getText().isEmpty()) {

            try {
                // Obtener los valores del formulario
                String nombre = txtNombre.getText();
                if (!c.buscar(nombre)) {  
                    JOptionPane.showMessageDialog(null, "El cliente ya fue eliminado o no existe en la base.");
                    return; 
                }
                
                   // Llamar al método delete con los parámetros adecuados
                    c.delete(nombre);
                    txtNombre.setText("");
                    txtEmail.setText("");
                    txtPhone.setText("");
                    txtDireccion.setText("");

                // Notificación de éxito (puedes personalizar el mensaje según sea necesario)
                JOptionPane.showMessageDialog(null, "Cliente eliminado exitosamente.");
                
            } catch (NumberFormatException e) {
                // Mostrar error si los parametro no son números válidos
                JOptionPane.showMessageDialog(null, "Por favor ingresa parametros válidos.");
            }
        } else {
            // Si alguno de los campos está vacío, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Validar que los campos no estén vacíos
        if (!txtNombre.getText().isEmpty() ) {
            try {
                // Obtener los valores del formulario
                String name = txtNombre.getText();
                String email = txtEmail.getText();
                String tel = txtPhone.getText();
                String direccion = txtDireccion.getText(); 
                String genero = (String) cmbGenero.getSelectedItem(); 

                // Verificar si el cliente existe en la base de datos
                if (!c.buscar(name)) {  
                    JOptionPane.showMessageDialog(null, "El cliente no existe en la base de datos.");
                    return; 
                }

                // Verificar que el teléfono tenga 10 dígitos o esté vacío
                if (tel.length() == 10 || tel.isEmpty()) {
                    // Verificar que el teléfono contenga solo números
                    if (tel.matches("\\d+") || tel.isEmpty()) {
                        // Llamada al método de actualización de la base de datos
                        c.update(name, genero, email, tel, direccion);
                    
                        // Limpiar los campos después de la actualización
                        txtNombre.setText("");
                        txtEmail.setText("");
                        txtPhone.setText("");
                        txtDireccion.setText("");

                        // Notificación de éxito
                        JOptionPane.showMessageDialog(null, "Cliente editado exitosamente.");
                    } else {
                        // Si el teléfono no es numérico
                        JOptionPane.showMessageDialog(null, "Por favor ingrese solo números en el número telefónico.");
                    }
                } else {
                    // Si el teléfono no tiene 10 dígitos
                    JOptionPane.showMessageDialog(null, "El número de teléfono debe contener 10 dígitos.");
                }
            } catch (NumberFormatException e) {
                // Mostrar error  no son valores válidos
                JOptionPane.showMessageDialog(null, "Por favor ingresa valores validos.");
            }
        } else {
            // Si alguno de los campos está vacío, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Validar que los campos no estén vacíos
        if ( !txtNombre.getText().isEmpty() ) {

            try {
                // Obtener los valores del formulario
                String name = txtNombre.getText();
                String Email = txtEmail.getText();
                String Tel=txtPhone.getText();
                String Direccion = txtDireccion.getText(); 
                String genero = (String) cmbGenero.getSelectedItem();
                if (c.buscar(name)) {  
                    JOptionPane.showMessageDialog(null, "El cliente ya existe en la base de datos.");
                    return; 
                }
                    if(Tel.length()==10||Tel.isEmpty()){
                        if(Tel.matches("\\d+")||Tel.isEmpty()){
                            c.add(name, genero, Email, Tel, Direccion);
                            txtNombre.setText("");
                            txtEmail.setText("");
                            txtPhone.setText("");
                            txtDireccion.setText("");
                            // Notificación de éxito (puedes personalizar el mensaje según sea necesario)
                            JOptionPane.showMessageDialog(null, "Cliente agregado exitosamente.");
                        }else{
                        JOptionPane.showMessageDialog( null,"Por favor ingrese solo numeros al numero telefonico");
                        }
                    }else{
                        JOptionPane.showMessageDialog( null,"El numero de telefono debe contener 10 Digitos");
                    }
                                
            } catch (NumberFormatException e) {
                // Mostrar error si hay un problema
                JOptionPane.showMessageDialog( null,"Por favor ingrese bien los parametros");
            }
        } else {
            // Si alguno de los campos está vacío, mostrar un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor completa todos los campos.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!"".equalsIgnoreCase(txtNombre.getText())) {
            int g=0;
            String nombre = txtNombre.getText();

            // Llamar al método select para obtener los productos correspondientes
            String[] Cliente = c.select(nombre);

            if (Cliente.length > 0 && Cliente[0] != null) {
                
               txtNombre.setText(Cliente[0]);

                String genero = Cliente[1];
               if ("M".equals(genero)) {
                    g=0;
                } else {
                    g=1;
                }
                cmbGenero.setSelectedIndex(g);
                txtEmail.setText(Cliente[2]);
                txtPhone.setText(Cliente[3]);
                txtDireccion.setText(Cliente[4]);
                
            } else {
                JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
                txtNombre.setText("");  
                txtEmail.setText("");    
                txtPhone.setText("");    
                txtDireccion.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el Nombre del Cliente.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblbackground1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
